[package]
name = "almacen"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.3", features = ["sqlite", "runtime-async-std-native-tls"]}
tokio = { version = "1.43", features = ["rt-multi-thread", "macros"] }
colored = { version = "3.0.0" }
dotenv = { version = "0.15" }
anyhow = { version = "1.0.95" }
cryptojs_rust = { version = "0.1.4" }
base64 = { version = "0.22.1" }
comfy-table = { version = "7.1.3" }
inquire = { version = "0.7.5" }