[package]
name = "almacen"
version = "2.0.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.7", features = ["sqlite"] }
libsqlite3-sys = { version = "0.31.0", features = ["bundled"] }
argon2 = "0.5.3"
colored = "3.0.0"
dotenvy = "0.15.7"
anyhow = "1.0.95"
base64 = "0.22.1"
comfy-table = "7.1.4"
inquire = "0.7.5"
csv = "1.3.1"
ring = "0.17.9"
zeroize = "1.8.1"